# Generated by Django 2.2.1 on 2019-05-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190516_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='num_units',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
